name: SDLC workflows
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: hashicorp/setup-terraform@v3

      - name: Install required packages
        id: bootstrap
        shell: bash
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
          wget https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64
          mv hadolint-Linux-x86_64 /usr/local/bin/hadolint
          chmod +x /usr/local/bin/hadolint

      - name: Checkov GitHub Action
        uses: bridgecrewio/checkov-action@v12
        with:
          quiet: true # optional: display only failed checks
          soft_fail: true # optional: do not return an error code if there are failed checks

      - uses: pre-commit/action@v3.0.1
      - name: Run sdlc/test
        id: test
        shell: bash
        run: |
          sdlc/test
